### ISSUE TITLE
Stabilization of 1.0.0

### ISSUE THREAD

**Issue by Srylax** [Srylax/mongodb-cursor-pagination#12]
@dvtkrlbs you were mentioning that you use this crate in production.
Is this application Open-Source?
I would like to test the new Beta release to further stabilize it.

**Comment by dvtkrlbs** [comment]
Unfortunately not i can test the new beta release internally and give feedback based on that. Right now we are on 0.3.2

**Comment by Srylax** [comment]
@dvtkrlbs That would be really nice! If you have any more suggestions or Feature Request I would be more than happy to add them.
